namespace Dom5Logic.Odm.Persistence.Models;

public class BaseU : IModel
{
    public int id { get; set; }
    public string name { get; set; }
    public int? wpn1 { get; set; }
    public int? wpn2 { get; set; }
    public int? wpn3 { get; set; }
    public int? wpn4 { get; set; }
    public int? wpn5 { get; set; }
    public int? wpn6 { get; set; }
    public int? wpn7 { get; set; }
    public int? armor1 { get; set; }
    public int? armor2 { get; set; }
    public int? armor3 { get; set; }
    public int? armor4 { get; set; }
    public int? rt { get; set; }
    public string? reclimit { get; set; }
    public int? basecost { get; set; }
    public int? rcost { get; set; }
    public int? size { get; set; }
    public int? ressize { get; set; }
    public int? hp { get; set; }
    public int? prot { get; set; }
    public int? mr { get; set; }
    public int? mor { get; set; }
    public int? str { get; set; }
    public int? att { get; set; }
    public int? def { get; set; }
    public int? prec { get; set; }
    public int? enc { get; set; }
    public int? mapmove { get; set; }
    public int? ap { get; set; }
    // public string? ambidextrous { get; set; }
    // public string? mounted { get; set; }
    // public string? reinvigoration { get; set; }
    // public int? leader { get; set; }
    // public string? undeadleader { get; set; }
    // public string? magicleader { get; set; }
    // public string? startage { get; set; }
    // public string? maxage { get; set; }
    // public int? hand { get; set; }
    // public int? head { get; set; }
    // public int? body { get; set; }
    // public int? foot { get; set; }
    // public int? misc { get; set; }
    // public string? crownonly { get; set; }
    // public string? pathcost { get; set; }
    // public string? startdom { get; set; }
    // public string? bonusspells { get; set; }
    // public string? F { get; set; }
    // public string? A { get; set; }
    // public string? W { get; set; }
    // public string? E { get; set; }
    // public string? S { get; set; }
    // public string? D { get; set; }
    // public string? N { get; set; }
    // public string? B { get; set; }
    // public string? H { get; set; }
    // public string? rand1 { get; set; }
    // public string? nbr1 { get; set; }
    // public string? link1 { get; set; }
    // public string? mask1 { get; set; }
    // public string? rand2 { get; set; }
    // public string? nbr2 { get; set; }
    // public string? link2 { get; set; }
    // public string? mask2 { get; set; }
    // public string? rand3 { get; set; }
    // public string? nbr3 { get; set; }
    // public string? link3 { get; set; }
    // public string? mask3 { get; set; }
    // public string? rand4 { get; set; }
    // public string? nbr4 { get; set; }
    // public string? link4 { get; set; }
    // public string? mask4 { get; set; }
    // public string? holy { get; set; }
    // public string? inquisitor { get; set; }
    // public string? mind { get; set; }
    // public string? inanimate { get; set; }
    // public string? undead { get; set; }
    // public string? demon { get; set; }
    // public string? magicbeing { get; set; }
    // public string? stonebeing { get; set; }
    // public string? animal { get; set; }
    // public string? coldblood { get; set; }
    // public string? female { get; set; }
    // public string? forestsurvival { get; set; }
    // public string? mountainsurvival { get; set; }
    // public string? wastesurvival { get; set; }
    // public string? swampsurvival { get; set; }
    // public string? cavesurvival { get; set; }
    // public string? aquatic { get; set; }
    // public string? amphibian { get; set; }
    // public string? pooramphibian { get; set; }
    // public string? floats { get; set; } //
    // public string? flying { get; set; }
    // public string? stormimmune { get; set; }
    // public string? teleport { get; set; }
    // public string? immobile { get; set; }
    // public string? noriverpass { get; set; }
    // public string? sailingshipsize { get; set; }
    // public string? sailingmaxunitsize { get; set; }
    // public string? stealthy { get; set; }
    // public string? illusion { get; set; }
    // public string? spy { get; set; }
    // public string? assassin { get; set; }
    // public string? patience { get; set; }
    // public string? seduce { get; set; }
    // public string? succubus { get; set; }
    // public string? corrupt { get; set; }
    // public string? heal { get; set; }
    // public string? immortal { get; set; }
    // public string? domimmortal { get; set; }
    // public string? reinc { get; set; }
    // public string? noheal { get; set; }
    // public string? neednoteat { get; set; }
    // public string? homesick { get; set; }
    // public string? undisciplined { get; set; }
    // public string? formationfighter { get; set; }
    // public string? slave { get; set; }
    // public string? standard { get; set; }
    // public string? inspirational { get; set; }
    // public string? taskmaster { get; set; }
    // public string? beastmaster { get; set; }
    // public string? bodyguard { get; set; }
    // public string? waterbreathing { get; set; }
    // public string? iceprot { get; set; }
    // public string? invulnerable { get; set; }
    // public string? slashres { get; set; }
    // public string? bluntres { get; set; }
    // public string? pierceres { get; set; }
    // public string? shockres { get; set; }
    // public string? fireres { get; set; }
    // public string? coldres { get; set; }
    // public string? poisonres { get; set; }
    // public string? voidsanity { get; set; }
    // public string? darkvision { get; set; }
    // public string? blind { get; set; }
    // public string? animalawe { get; set; }
    // public string? awe { get; set; }
    // public string? haltheretic { get; set; }
    // public string? fear { get; set; }
    // public string? berserk { get; set; }
    // public string? cold { get; set; }
    // public string? heat { get; set; }
    // public string? fireshield { get; set; }
    // public string? banefireshield { get; set; }
    // public string? damagerev { get; set; }
    // public string? poisoncloud { get; set; }
    // public string? diseasecloud { get; set; }
    // public string? slimer { get; set; }
    // public string? mindslime { get; set; }
    // public string? reform { get; set; }
    // public string? regeneration { get; set; }
    // public string? reanimator { get; set; }
    // public string? poisonarmor { get; set; }
    // public string? petrify { get; set; }
    // public string? eyeloss { get; set; }
    // public string? ethereal { get; set; }
    // public string? ethtrue { get; set; }
    // public string? deathcurse { get; set; }
    // public string? trample { get; set; }
    // public string? trampswallow { get; set; }
    // public string? stormpower { get; set; }
    // public string? firepower { get; set; }
    // public string? coldpower { get; set; }
    // public string? darkpower { get; set; }
    // public string? chaospower { get; set; }
    // public string? magicpower { get; set; }
    // public string? winterpower { get; set; }//
    // public string? springpower { get; set; }
    // public string? summerpower { get; set; }
    // public string? fallpower { get; set; }
    // public string? forgebonus { get; set; }
    // public string? fixforgebonus { get; set; }
    // public string? mastersmith { get; set; }
    // public string? resources { get; set; }
    // public string? autohealer { get; set; }
    // public string? autodishealer { get; set; }
    // public string? alch { get; set; }
    // public string? nobadevents { get; set; }
    // public string? events { get; set; }//
    // public string? insane { get; set; }
    // public string? shatteredsoul { get; set; }
    // public string? leper { get; set; }
    // public string? taxcollector { get; set; }
    // public string? gem { get; set; }
    // public string? gemprod { get; set; }
    // public string? chaosrec { get; set; }
    // public string? pillagebonus { get; set; }
    // public string? patrolbonus { get; set; }
    // public string? castledef { get; set; }
    // public string? siegebonus { get; set; }
    // public string? incprovdef { get; set; }
    // public string? supplybonus { get; set; }
    // public string? incunrest { get; set; }
    // public string? popkill { get; set; }
    // public string? researchbonus { get; set; }
    // public string? drainimmune { get; set; }
    // public string? inspiringres { get; set; }
    // public string? douse { get; set; }
    // public string? adeptsacr { get; set; }
    // public string? crossbreeder { get; set; }
    // public string? makepearls { get; set; }
    // public string? pathboost { get; set; }
    // public string? allrange { get; set; }
    // public string? voidsum { get; set; }
    // public string? heretic { get; set; }
    // public string? elegist { get; set; }
    // public string? shapechange { get; set; }
    // public string? firstshape { get; set; }
    // public string? secondshape { get; set; }
    // public string? secondtmpshape { get; set; }
    // public string? landshape { get; set; }
    // public string? watershape { get; set; }
    // public string? forestshape { get; set; }
    // public string? plainshape { get; set; }
    // public string? xpshape { get; set; }
    // public string? unique { get; set; }
    // public string? fixedname { get; set; }
    // public string? special { get; set; }
    // public string? nametype { get; set; }
    // public string? summon { get; set; }
    // public string? n_summon { get; set; }
    // public string? autosum { get; set; }
    // public string? n_autosum { get; set; }
    // public string? batstartsum1 { get; set; }
    // public string? batstartsum2 { get; set; }
    // public string? domsummon { get; set; }
    // public string? domsummon20 { get; set; }
    // public string? raredomsummon { get; set; }
    // public string? bloodvengeance { get; set; }
    // public string? bringeroffortune { get; set; }
    // public string? realm1 { get; set; }
    // public string? realm2 { get; set; }
    // public string? realm3 { get; set; }
    // public string? batstartsum3 { get; set; }
    // public string? batstartsum4 { get; set; }
    // public string? batstartsum5 { get; set; }
    // public string? batstartsum1d6 { get; set; }
    // public string? batstartsum2d6 { get; set; }
    // public string? batstartsum3d6 { get; set; }
    // public string? batstartsum4d6 { get; set; }
    // public string? batstartsum5d6 { get; set; }
    // public string? batstartsum6d6 { get; set; }
    // public string? turmoilsummon { get; set; }
    // public string? coldsummon { get; set; }
    // public string? scalewalls { get; set; }
    // public string? deathfire { get; set; }
    // public string? uwregen { get; set; }
    // public string? shrinkhp { get; set; }
    // public string? growhp { get; set; }
    // public string? transformation { get; set; }
    // public string? startingaff { get; set; }
    // public string? fixedresearch { get; set; }
    // public string? divineins { get; set; }
    // public string? lamialord { get; set; }
    // public string? preanimator { get; set; }
    // public string? dreanimator { get; set; }
    // public string? mummify { get; set; }
    // public string? onebattlespell { get; set; }
    // public string? fireattuned { get; set; }
    // public string? airattuned { get; set; }
    // public string? waterattuned { get; set; }
    // public string? earthattuned { get; set; }
    // public string? astralattuned { get; set; }
    // public string? deathattuned { get; set; }
    // public string? natureattuned { get; set; }
    // public string? bloodattuned { get; set; }
    // public string? magicboostF { get; set; }
    // public string? magicboostA { get; set; }
    // public string? magicboostW { get; set; }
    // public string? magicboostE { get; set; }
    // public string? magicboostS { get; set; }
    // public string? magicboostD { get; set; }
    // public string? magicboostN { get; set; }
    // public string? magicboostALL { get; set; }
    // public string? eyes { get; set; }
    // public string? heatrec { get; set; }
    // public string? coldrec { get; set; }
    // public string? spreadchaos { get; set; }
    // public string? spreaddeath { get; set; }
    // public string? corpseeater { get; set; }
    // public string? poisonskin { get; set; }
    // public string? bug { get; set; }
    // public string? uwbug { get; set; }
    // public string? spreadorder { get; set; }
    // public string? spreadgrowth { get; set; }
    // public string? startitem { get; set; }
    // public string? spreaddom { get; set; }
    // public string? battlesum5 { get; set; }
    // public string? acidshield { get; set; }
    // public string? drake { get; set; }
    // public string? prophetshape { get; set; }
    // public string? horror { get; set; }
    // public string? enchrebate50p { get; set; }
    // public string? latehero { get; set; }
    // public string? sailsize { get; set; }
    // public string? uwdamage { get; set; }
    // public string? landdamage { get; set; }
    // public int? rpcost { get; set; }
    // public string? buffer { get; set; }
    // public string? rand5 { get; set; }
    // public string? nbr5 { get; set; }
    // public string? link5 { get; set; }
    // public string? mask5 { get; set; }
    // public string? rand6 { get; set; }
    // public string? nbr6 { get; set; }
    // public string? link6 { get; set; }
    // public string? mask6 { get; set; }
    // public string? mummification { get; set; }
    // public string? diseaseres { get; set; }
    // public string? raiseonkill { get; set; }
    // public string? raiseshape { get; set; }
    // public string? sendlesserhorrormult { get; set; }
    // public string? xploss { get; set; }
    // public string? theftofthesunawe { get; set; }
    // public string? incorporate { get; set; }
    // public string? hpoverslow { get; set; }
    // public string? blessbers { get; set; }
    // public string? dragonlord { get; set; }
    // public string? curseattacker { get; set; }
    // public string? uwheat { get; set; }
    // public string? slothresearch { get; set; }
    // public string? horrordeserter { get; set; }
    // public string? mindvessel { get; set; }
    // public string? elementrange { get; set; }
    // public string? sorceryrange { get; set; }
    // public string? older { get; set; }
    // public string? disbelieve { get; set; }
    // public string? firerange { get; set; }
    // public string? astralrange { get; set; }
    // public string? landreinvigoration { get; set; }
    // public string? naturerange { get; set; }
    // public string? beartattoo { get; set; }
    // public string? horsetattoo { get; set; }
    // public string? reincarnation { get; set; }
    // public string? wolftattoo { get; set; }
    // public string? boartattoo { get; set; }
    // public string? sleepaura { get; set; }
    // public string? snaketattoo { get; set; }
    // public string? appetite { get; set; }
    // public string? astralfetters { get; set; }
    // public string? foreignmagicboost { get; set; }
    // public string? templetrainer { get; set; }
    // public string? infernoret { get; set; }
    // public string? kokytosret { get; set; }
    // public string? addrandomage { get; set; }
    // public string? unsurr { get; set; }
    // public string? combatcaster { get; set; }
    // public string? homeshape { get; set; }
    // public string? speciallook { get; set; }
    // public string? aisinglerec { get; set; }
    // public string? nowish { get; set; }
    // public string? bugreform { get; set; }
    // public string? mason { get; set; }
    // public string? onisummon { get; set; }
    // public string? sunawe { get; set; }
    // public string? spiritsight { get; set; }
    // public string? defenceorganiser { get; set; }
    // public string? invisible { get; set; }
    // public string? startaff { get; set; }
    // public string? ivylord { get; set; }
    // public string? spellsinger { get; set; }
    // public string? magicstudy { get; set; }
    // public string? triplegod { get; set; }
    // public string? triplegodmag { get; set; }
    // public string? unify { get; set; }
    // public string? triple3mon { get; set; }
    // public string? yearturn { get; set; }
    // public string? fortkill { get; set; }
    // public string? thronekill { get; set; }
    // public string? digest { get; set; }
    // public string? indepmove { get; set; }
    // public string? unteleportable { get; set; }
    // public string? reanimpriest { get; set; }
    // public string? stunimmunity { get; set; }
    // public string? entangle { get; set; }
    // public string? alchemy { get; set; }
    // public string? woundfend { get; set; }
    // public string? singlebattle { get; set; }
    // public string? falsearmy { get; set; }
    // public string? summon5 { get; set; }
    // public string? ainorec { get; set; }
    // public string? researchwithoutmagic { get; set; }
    // public string? slaver { get; set; }
    // public string? autocompete { get; set; }
    // public string? deathparalyze { get; set; }
    // public string? adventurers { get; set; }
    // public string? cleanshape { get; set; }
    // public string? reqlab { get; set; }
    // public string? reqtemple { get; set; }
    // public string? horrormarked { get; set; }
    // public string? changetargetgenderforseductionandseductionimmune { get; set; }
    // public string? corpseconstruct { get; set; }
    // public string? guardianspiritmodifier { get; set; }
    // public string? isashah { get; set; }
    // public string? iceforging { get; set; }
    // public string? isayazad { get; set; }
    // public string? isadaeva { get; set; }
    // public string? blessfly { get; set; }
    // public string? plant { get; set; }
    // public string? clockworklord { get; set; }
    // public string? commaster { get; set; }
    // public string? comslave { get; set; }
    // public string? minsizeleader { get; set; }
    // public string? snowmove { get; set; }
    // public string? swimming { get; set; }
    // public string? stupid { get; set; }
    // public string? skirmisher { get; set; }
    // public string? ironvul { get; set; }
    // public string? heathensummon { get; set; }
    // public string? unseen { get; set; }
    // public string? illusionary { get; set; }
    // public string? reformtime { get; set; }
    // public string? immortalrespawn { get; set; }
    // public string? nomovepen { get; set; }
    // public string? wolf { get; set; }
    // public string? dungeon { get; set; }
    // public string? graphicsize { get; set; }
    // public string? twiceborn { get; set; }
    // public string? aboleth { get; set; }
    // public string? tmpastralgems { get; set; }
    // public string? localsun { get; set; }
    // public string? tmpfiregems { get; set; }
    // public string? defiler { get; set; }
    // public string? mountedbeserk { get; set; }
    // public string? lanceok { get; set; }
    // public string? startheroab { get; set; }
    // public string? minprison { get; set; }
    // public string? uwfireshield { get; set; }
    // public string? saltvul { get; set; }
    // public string? landenc { get; set; }
    // public string? plaguedoctor { get; set; }
    // public string? curseluckshield { get; set; }
    // public string? pathboostuw { get; set; }
    // public string? pathboostland { get; set; }
    // public string? noarmormapmovepenalty { get; set; }
    // public string? farthronekill { get; set; }
    // public string? hpoverflow { get; set; }
    // public string? indepstay { get; set; }
    // public string? polyimmune { get; set; }
    // public string? horrormark { get; set; }
    // public string? deathdisease { get; set; }
    // public string? allret { get; set; }
    // public string? percentpathreduction { get; set; }
    // public string? aciddigest { get; set; }
    // public string? beckon { get; set; }
    // public string? slaverbonus { get; set; }
    // public string? carcasscollector { get; set; }
    // public string? mindcollar { get; set; }
    // public string? labpromotion { get; set; }
    // public string? mountainrec { get; set; }
    // public string? indepspells { get; set; }
    // public string? enchrebate50 { get; set; }
    // public string? summon1 { get; set; }
    // public string? randomspell { get; set; }
    // public string? deathpower { get; set; }
    // public string? deathrec { get; set; }
    // public string? norange { get; set; }
    // public string? insanify { get; set; }
    // public string? reanimator2 { get; set; } //
    // public string? defector { get; set; }
    // public string? nohof { get; set; }
    // public string? batstartsum1d3 { get; set; }
    // public string? enchrebate10 { get; set; }
    // public string? undying { get; set; }
    // public string? moralebonus { get; set; }
    // public string? uncurableaffliction { get; set; }
    // public string? autoblessed { get; set; }
    // public string? wintersummon1d3 { get; set; } //
    // public string? stygianguide { get; set; }
    // public string? almostundead { get; set; }
    // public string? end { get; set; }
}