using System;
using System.Collections.Generic;

namespace Dom5Logic.Model
{
    public partial class BaseUDb
    {
        public string? Id { get; set; }
        public string? Name { get; set; }
        public string? Wpn1 { get; set; }
        public string? Wpn2 { get; set; }
        public string? Wpn3 { get; set; }
        public string? Wpn4 { get; set; }
        public string? Wpn5 { get; set; }
        public string? Wpn6 { get; set; }
        public string? Wpn7 { get; set; }
        public string? Armor1 { get; set; }
        public string? Armor2 { get; set; }
        public string? Armor3 { get; set; }
        public string? Armor4 { get; set; }
        public string? Rt { get; set; }
        public string? Reclimit { get; set; }
        public string? Basecost { get; set; }
        public string? Rcost { get; set; }
        public string? Size { get; set; }
        public string? Ressize { get; set; }
        public string? Hp { get; set; }
        public string? Prot { get; set; }
        public string? Mr { get; set; }
        public string? Mor { get; set; }
        public string? Str { get; set; }
        public string? Att { get; set; }
        public string? Def { get; set; }
        public string? Prec { get; set; }
        public string? Enc { get; set; }
        public string? Mapmove { get; set; }
        public string? Ap { get; set; }
        public string? Ambidextrous { get; set; }
        public string? Mounted { get; set; }
        public string? Reinvigoration { get; set; }
        public string? Leader { get; set; }
        public string? Undeadleader { get; set; }
        public string? Magicleader { get; set; }
        public string? Startage { get; set; }
        public string? Maxage { get; set; }
        public string? Hand { get; set; }
        public string? Head { get; set; }
        public string? Body { get; set; }
        public string? Foot { get; set; }
        public string? Misc { get; set; }
        public string? Crownonly { get; set; }
        public string? Pathcost { get; set; }
        public string? Startdom { get; set; }
        public string? Bonusspells { get; set; }
        public string? F { get; set; }
        public string? A { get; set; }
        public string? W { get; set; }
        public string? E { get; set; }
        public string? S { get; set; }
        public string? D { get; set; }
        public string? N { get; set; }
        public string? B { get; set; }
        public string? H { get; set; }
        public string? Rand1 { get; set; }
        public string? Nbr1 { get; set; }
        public string? Link1 { get; set; }
        public string? Mask1 { get; set; }
        public string? Rand2 { get; set; }
        public string? Nbr2 { get; set; }
        public string? Link2 { get; set; }
        public string? Mask2 { get; set; }
        public string? Rand3 { get; set; }
        public string? Nbr3 { get; set; }
        public string? Link3 { get; set; }
        public string? Mask3 { get; set; }
        public string? Rand4 { get; set; }
        public string? Nbr4 { get; set; }
        public string? Link4 { get; set; }
        public string? Mask4 { get; set; }
        public string? Holy { get; set; }
        public string? Inquisitor { get; set; }
        public string? Mind { get; set; }
        public string? Inanimate { get; set; }
        public string? Undead { get; set; }
        public string? Demon { get; set; }
        public string? Magicbeing { get; set; }
        public string? Stonebeing { get; set; }
        public string? Animal { get; set; }
        public string? Coldblood { get; set; }
        public string? Female { get; set; }
        public string? Forestsurvival { get; set; }
        public string? Mountainsurvival { get; set; }
        public string? Wastesurvival { get; set; }
        public string? Swampsurvival { get; set; }
        public string? Cavesurvival { get; set; }
        public string? Aquatic { get; set; }
        public string? Amphibian { get; set; }
        public string? Pooramphibian { get; set; }
        public string? Float { get; set; }
        public string? Flying { get; set; }
        public string? Stormimmune { get; set; }
        public string? Teleport { get; set; }
        public string? Immobile { get; set; }
        public string? Noriverpass { get; set; }
        public string? Sailingshipsize { get; set; }
        public string? Sailingmaxunitsize { get; set; }
        public string? Stealthy { get; set; }
        public string? Illusion { get; set; }
        public string? Spy { get; set; }
        public string? Assassin { get; set; }
        public string? Patience { get; set; }
        public string? Seduce { get; set; }
        public string? Succubus { get; set; }
        public string? Corrupt { get; set; }
        public string? Heal { get; set; }
        public string? Immortal { get; set; }
        public string? Domimmortal { get; set; }
        public string? Reinc { get; set; }
        public string? Noheal { get; set; }
        public string? Neednoteat { get; set; }
        public string? Homesick { get; set; }
        public string? Undisciplined { get; set; }
        public string? Formationfighter { get; set; }
        public string? Slave { get; set; }
        public string? Standard { get; set; }
        public string? Inspirational { get; set; }
        public string? Taskmaster { get; set; }
        public string? Beastmaster { get; set; }
        public string? Bodyguard { get; set; }
        public string? Waterbreathing { get; set; }
        public string? Iceprot { get; set; }
        public string? Invulnerable { get; set; }
        public string? Slashres { get; set; }
        public string? Bluntres { get; set; }
        public string? Pierceres { get; set; }
        public string? Shockres { get; set; }
        public string? Fireres { get; set; }
        public string? Coldres { get; set; }
        public string? Poisonres { get; set; }
        public string? Voidsanity { get; set; }
        public string? Darkvision { get; set; }
        public string? Blind { get; set; }
        public string? Animalawe { get; set; }
        public string? Awe { get; set; }
        public string? Haltheretic { get; set; }
        public string? Fear { get; set; }
        public string? Berserk { get; set; }
        public string? Cold { get; set; }
        public string? Heat { get; set; }
        public string? Fireshield { get; set; }
        public string? Banefireshield { get; set; }
        public string? Damagerev { get; set; }
        public string? Poisoncloud { get; set; }
        public string? Diseasecloud { get; set; }
        public string? Slimer { get; set; }
        public string? Mindslime { get; set; }
        public string? Reform { get; set; }
        public string? Regeneration { get; set; }
        public string? Reanimator { get; set; }
        public string? Poisonarmor { get; set; }
        public string? Petrify { get; set; }
        public string? Eyeloss { get; set; }
        public string? Ethereal { get; set; }
        public string? Ethtrue { get; set; }
        public string? Deathcurse { get; set; }
        public string? Trample { get; set; }
        public string? Trampswallow { get; set; }
        public string? Stormpower { get; set; }
        public string? Firepower { get; set; }
        public string? Coldpower { get; set; }
        public string? Darkpower { get; set; }
        public string? Chaospower { get; set; }
        public string? Magicpower { get; set; }
        public string? Winterpower { get; set; }
        public string? Springpower { get; set; }
        public string? Summerpower { get; set; }
        public string? Fallpower { get; set; }
        public string? Forgebonus { get; set; }
        public string? Fixforgebonus { get; set; }
        public string? Mastersmith { get; set; }
        public string? Resources { get; set; }
        public string? Autohealer { get; set; }
        public string? Autodishealer { get; set; }
        public string? Alch { get; set; }
        public string? Nobadevents { get; set; }
        public string? Event { get; set; }
        public string? Insane { get; set; }
        public string? Shatteredsoul { get; set; }
        public string? Leper { get; set; }
        public string? Taxcollector { get; set; }
        public string? Gem { get; set; }
        public string? Gemprod { get; set; }
        public string? Chaosrec { get; set; }
        public string? Pillagebonus { get; set; }
        public string? Patrolbonus { get; set; }
        public string? Castledef { get; set; }
        public string? Siegebonus { get; set; }
        public string? Incprovdef { get; set; }
        public string? Supplybonus { get; set; }
        public string? Incunrest { get; set; }
        public string? Popkill { get; set; }
        public string? Researchbonus { get; set; }
        public string? Drainimmune { get; set; }
        public string? Inspiringres { get; set; }
        public string? Douse { get; set; }
        public string? Adeptsacr { get; set; }
        public string? Crossbreeder { get; set; }
        public string? Makepearls { get; set; }
        public string? Pathboost { get; set; }
        public string? Allrange { get; set; }
        public string? Voidsum { get; set; }
        public string? Heretic { get; set; }
        public string? Elegist { get; set; }
        public string? Shapechange { get; set; }
        public string? Firstshape { get; set; }
        public string? Secondshape { get; set; }
        public string? Secondtmpshape { get; set; }
        public string? Landshape { get; set; }
        public string? Watershape { get; set; }
        public string? Forestshape { get; set; }
        public string? Plainshape { get; set; }
        public string? Xpshape { get; set; }
        public string? Unique { get; set; }
        public string? Fixedname { get; set; }
        public string? Special { get; set; }
        public string? Nametype { get; set; }
        public string? Summon { get; set; }
        public string? NSummon { get; set; }
        public string? Autosum { get; set; }
        public string? NAutosum { get; set; }
        public string? Batstartsum1 { get; set; }
        public string? Batstartsum2 { get; set; }
        public string? Domsummon { get; set; }
        public string? Domsummon20 { get; set; }
        public string? Raredomsummon { get; set; }
        public string? Bloodvengeance { get; set; }
        public string? Bringeroffortune { get; set; }
        public string? Realm1 { get; set; }
        public string? Realm2 { get; set; }
        public string? Realm3 { get; set; }
        public string? Batstartsum3 { get; set; }
        public string? Batstartsum4 { get; set; }
        public string? Batstartsum5 { get; set; }
        public string? Batstartsum1d6 { get; set; }
        public string? Batstartsum2d6 { get; set; }
        public string? Batstartsum3d6 { get; set; }
        public string? Batstartsum4d6 { get; set; }
        public string? Batstartsum5d6 { get; set; }
        public string? Batstartsum6d6 { get; set; }
        public string? Turmoilsummon { get; set; }
        public string? Coldsummon { get; set; }
        public string? Scalewalls { get; set; }
        public string? Deathfire { get; set; }
        public string? Uwregen { get; set; }
        public string? Shrinkhp { get; set; }
        public string? Growhp { get; set; }
        public string? Transformation { get; set; }
        public string? Startingaff { get; set; }
        public string? Fixedresearch { get; set; }
        public string? Divineins { get; set; }
        public string? Lamialord { get; set; }
        public string? Preanimator { get; set; }
        public string? Dreanimator { get; set; }
        public string? Mummify { get; set; }
        public string? Onebattlespell { get; set; }
        public string? Fireattuned { get; set; }
        public string? Airattuned { get; set; }
        public string? Waterattuned { get; set; }
        public string? Earthattuned { get; set; }
        public string? Astralattuned { get; set; }
        public string? Deathattuned { get; set; }
        public string? Natureattuned { get; set; }
        public string? Bloodattuned { get; set; }
        public string? MagicboostF { get; set; }
        public string? MagicboostA { get; set; }
        public string? MagicboostW { get; set; }
        public string? MagicboostE { get; set; }
        public string? MagicboostS { get; set; }
        public string? MagicboostD { get; set; }
        public string? MagicboostN { get; set; }
        public string? MagicboostAll { get; set; }
        public string? Eyes { get; set; }
        public string? Heatrec { get; set; }
        public string? Coldrec { get; set; }
        public string? Spreadchaos { get; set; }
        public string? Spreaddeath { get; set; }
        public string? Corpseeater { get; set; }
        public string? Poisonskin { get; set; }
        public string? Bug { get; set; }
        public string? Uwbug { get; set; }
        public string? Spreadorder { get; set; }
        public string? Spreadgrowth { get; set; }
        public string? Startitem { get; set; }
        public string? Spreaddom { get; set; }
        public string? Battlesum5 { get; set; }
        public string? Acidshield { get; set; }
        public string? Drake { get; set; }
        public string? Prophetshape { get; set; }
        public string? Horror { get; set; }
        public string? Enchrebate50p { get; set; }
        public string? Latehero { get; set; }
        public string? Sailsize { get; set; }
        public string? Uwdamage { get; set; }
        public string? Landdamage { get; set; }
        public string? Rpcost { get; set; }
        public string? Buffer { get; set; }
        public string? Rand5 { get; set; }
        public string? Nbr5 { get; set; }
        public string? Link5 { get; set; }
        public string? Mask5 { get; set; }
        public string? Rand6 { get; set; }
        public string? Nbr6 { get; set; }
        public string? Link6 { get; set; }
        public string? Mask6 { get; set; }
        public string? Mummification { get; set; }
        public string? Diseaseres { get; set; }
        public string? Raiseonkill { get; set; }
        public string? Raiseshape { get; set; }
        public string? Sendlesserhorrormult { get; set; }
        public string? Xploss { get; set; }
        public string? Theftofthesunawe { get; set; }
        public string? Incorporate { get; set; }
        public string? Hpoverslow { get; set; }
        public string? Blessbers { get; set; }
        public string? Dragonlord { get; set; }
        public string? Curseattacker { get; set; }
        public string? Uwheat { get; set; }
        public string? Slothresearch { get; set; }
        public string? Horrordeserter { get; set; }
        public string? Mindvessel { get; set; }
        public string? Elementrange { get; set; }
        public string? Sorceryrange { get; set; }
        public string? Older { get; set; }
        public string? Disbelieve { get; set; }
        public string? Firerange { get; set; }
        public string? Astralrange { get; set; }
        public string? Landreinvigoration { get; set; }
        public string? Naturerange { get; set; }
        public string? Beartattoo { get; set; }
        public string? Horsetattoo { get; set; }
        public string? Reincarnation { get; set; }
        public string? Wolftattoo { get; set; }
        public string? Boartattoo { get; set; }
        public string? Sleepaura { get; set; }
        public string? Snaketattoo { get; set; }
        public string? Appetite { get; set; }
        public string? Astralfetters { get; set; }
        public string? Foreignmagicboost { get; set; }
        public string? Templetrainer { get; set; }
        public string? Infernoret { get; set; }
        public string? Kokytosret { get; set; }
        public string? Addrandomage { get; set; }
        public string? Unsurr { get; set; }
        public string? Combatcaster { get; set; }
        public string? Homeshape { get; set; }
        public string? Speciallook { get; set; }
        public string? Aisinglerec { get; set; }
        public string? Nowish { get; set; }
        public string? Bugreform { get; set; }
        public string? Mason { get; set; }
        public string? Onisummon { get; set; }
        public string? Sunawe { get; set; }
        public string? Spiritsight { get; set; }
        public string? Defenceorganiser { get; set; }
        public string? Invisible { get; set; }
        public string? Startaff { get; set; }
        public string? Ivylord { get; set; }
        public string? Spellsinger { get; set; }
        public string? Magicstudy { get; set; }
        public string? Triplegod { get; set; }
        public string? Triplegodmag { get; set; }
        public string? Unify { get; set; }
        public string? Triple3mon { get; set; }
        public string? Yearturn { get; set; }
        public string? Fortkill { get; set; }
        public string? Thronekill { get; set; }
        public string? Digest { get; set; }
        public string? Indepmove { get; set; }
        public string? Unteleportable { get; set; }
        public string? Reanimpriest { get; set; }
        public string? Stunimmunity { get; set; }
        public string? Entangle { get; set; }
        public string? Alchemy { get; set; }
        public string? Woundfend { get; set; }
        public string? Singlebattle { get; set; }
        public string? Falsearmy { get; set; }
        public string? Summon5 { get; set; }
        public string? Ainorec { get; set; }
        public string? Researchwithoutmagic { get; set; }
        public string? Slaver { get; set; }
        public string? Autocompete { get; set; }
        public string? Deathparalyze { get; set; }
        public string? Adventurers { get; set; }
        public string? Cleanshape { get; set; }
        public string? Reqlab { get; set; }
        public string? Reqtemple { get; set; }
        public string? Horrormarked { get; set; }
        public string? Changetargetgenderforseductionandseductionimmune { get; set; }
        public string? Corpseconstruct { get; set; }
        public string? Guardianspiritmodifier { get; set; }
        public string? Isashah { get; set; }
        public string? Iceforging { get; set; }
        public string? Isayazad { get; set; }
        public string? Isadaeva { get; set; }
        public string? Blessfly { get; set; }
        public string? Plant { get; set; }
        public string? Clockworklord { get; set; }
        public string? Commaster { get; set; }
        public string? Comslave { get; set; }
        public string? Minsizeleader { get; set; }
        public string? Snowmove { get; set; }
        public string? Swimming { get; set; }
        public string? Stupid { get; set; }
        public string? Skirmisher { get; set; }
        public string? Ironvul { get; set; }
        public string? Heathensummon { get; set; }
        public string? Unseen { get; set; }
        public string? Illusionary { get; set; }
        public string? Reformtime { get; set; }
        public string? Immortalrespawn { get; set; }
        public string? Nomovepen { get; set; }
        public string? Wolf { get; set; }
        public string? Dungeon { get; set; }
        public string? Graphicsize { get; set; }
        public string? Twiceborn { get; set; }
        public string? Aboleth { get; set; }
        public string? Tmpastralgems { get; set; }
        public string? Localsun { get; set; }
        public string? Tmpfiregems { get; set; }
        public string? Defiler { get; set; }
        public string? Mountedbeserk { get; set; }
        public string? Lanceok { get; set; }
        public string? Startheroab { get; set; }
        public string? Minprison { get; set; }
        public string? Uwfireshield { get; set; }
        public string? Saltvul { get; set; }
        public string? Landenc { get; set; }
        public string? Plaguedoctor { get; set; }
        public string? Curseluckshield { get; set; }
        public string? Pathboostuw { get; set; }
        public string? Pathboostland { get; set; }
        public string? Noarmormapmovepenalty { get; set; }
        public string? Farthronekill { get; set; }
        public string? Hpoverflow { get; set; }
        public string? Indepstay { get; set; }
        public string? Polyimmune { get; set; }
        public string? Horrormark { get; set; }
        public string? Deathdisease { get; set; }
        public string? Allret { get; set; }
        public string? Percentpathreduction { get; set; }
        public string? Aciddigest { get; set; }
        public string? Beckon { get; set; }
        public string? Slaverbonus { get; set; }
        public string? Carcasscollector { get; set; }
        public string? Mindcollar { get; set; }
        public string? Labpromotion { get; set; }
        public string? Mountainrec { get; set; }
        public string? Indepspells { get; set; }
        public string? Enchrebate50 { get; set; }
        public string? Summon1 { get; set; }
        public string? Randomspell { get; set; }
        public string? Deathpower { get; set; }
        public string? Deathrec { get; set; }
        public string? Norange { get; set; }
        public string? Insanify { get; set; }
        public string? Reanimator2 { get; set; }
        public string? Defector { get; set; }
        public string? Nohof { get; set; }
        public string? Batstartsum1d3 { get; set; }
        public string? Enchrebate10 { get; set; }
        public string? Undying { get; set; }
        public string? Moralebonus { get; set; }
        public string? Uncurableaffliction { get; set; }
        public string? Autoblessed { get; set; }
        public string? Wintersummon1d3 { get; set; }
        public string? Stygianguide { get; set; }
        public string? Almostundead { get; set; }
        public string? End { get; set; }
    }
}
